version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx_etc/conf.d:/etc/nginx/conf.d:rw
      - ./nginx_etc/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./index.html:/usr/share/nginx/html/index.html:rw
      - ./certs:/etc/nginx/cert_files
    restart: unless-stopped
